    let info = [
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
            num: "001",
            title: "Bulbasaur",
            dex: "Por algum tempo após seu nascimento, ele utiliza os nutrientes que estão contidos na semente em seu dorso para crescer.",
            type: "./assets/grass.png",
            type2: "./assets/poison.png",
            ability:"Overgrow",
            ability2: "none",
            hiddenabilitie:"Clorophyll",
            link:"https://pokemondb.net/pokedex/bulbasaur"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
            num: "002",
            title: "Ivysaur",
            dex: "Quanto mais luz solar Ivysaur abssorve, mais força surge dentro dele, permitindo que o broto em suas costas cresça.",
            type: "./assets/grass.png",
            type2: "./assets/poison.png",
            ability: "Overgrow",
            ability2: "none",
            hiddenabilitie: "Clorophyll",
            link:"https://pokemondb.net/pokedex/ivysaur"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
            num: "003",
            title: "Venusaur",
            dex: "Enquanto se aquece ao sol, pode converter a luz em energia. Como resultado, é mais forte no verão.",
            type: "./assets/grass.png",
            type2: "./assets/poison.png",
            ability: "Overgrow",
            ability2: "none",
            hiddenabilitie: "Clorophyll",
            link:"https://pokemondb.net/pokedex/venusaur"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
            num: "004",
            title: "Charmander",
            dex: "A chama em sua cauda mostra a força de sua força vital. Se Charmander estiver fraco, a chama também queimará fracamente.",
            type: "./assets/fire.png",
            type2: "none",
            ability: "Blaze",
            ability2: "none",
            hiddenabilitie: "Solar Power",
            link:"https://pokemondb.net/pokedex/charmander"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
            num: "005",
            title: "Charmeleon",
            dex: "Quando ele balança sua cauda em chamas, a temperatura ao seu redor aumenta cada vez mais, atormentando seus oponentes.",
            type: "./assets/fire.png",
            type2: "none",
            ability: "Blaze",
            ability2: "none",
            hiddenabilitie: "Solar Power",
            link:"https://pokemondb.net/pokedex/charmeleon"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
            num: "006",
            title: "Charizard",
            dex: "Se Charizard ficar irritado, a chama na ponta de sua cauda queima em um tom azul claro.",
            type: "./assets/fire.png",
            type2: "./assets/flying.png",
            ability: "Blaze",
            ability2: "none",
            hiddenabilitie: "Solar Power",
            link:"https://pokemondb.net/pokedex/charizard"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
            num: "007",
            title: "Squirtle",
            dex: "Após o nascimento, suas costas incham e endurecem formando uma concha. Ele dispara um jato potente pela boca.",
            type: "./assets/water.png",
            type2: "none",
            ability: "Torrent",
            ability2: "none",
            hiddenabilitie: "Rain Dish",
            link:"https://pokemondb.net/pokedex/squirtle"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
            num: "008",
            title: "Wartortle",
            dex: "A cauda longa e peluda de Wartortle é um símbolo de longevidade, por isso este Pokémon é bastante popular entre os idosos.",
            type: "./assets/water.png",
            type2: "none",
            ability: "Torrent",
            ability2: "none",
            hiddenabilitie: "Raind Dish",
            link:"https://pokemondb.net/pokedex/wartortle"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
            num: "009",
            title: "Blastoise",
            dex: "Ele aumenta deliberadamente o peso do corpo para poder suportar o recuo dos jatos de água que dispara",
            type: "./assets/water.png",
            type2: "none",
            ability: "Torrent",
            ability2: "none",
            hiddenabilitie: "Rain Dish",
            link:"https://pokemondb.net/pokedex/blastoise"
        },
        {
            ft: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
            num: "025",
            title: "Pikachu",
            dex: "Quando está irritado, descarrega imediatamente a energia armazenada em suas bochechas.",
            type: "./assets/electric.png",
            type2: "none",
            ability: "Static",
            ability2: "none",
            hiddenabilitie: "Lightning Rod",
            link:"https://pokemondb.net/pokedex/pikachu"
        },
]